### ISSUE TITLE
Core pins dataclasses to outdated version

### ISSUE THREAD

**Issue by jmcarp** [fishtown-analytics/hologram#39]
### Describe the bug

https://github.com/fishtown-analytics/dbt/blob/dev/margaret-mead/core/setup.py#L72 pins dataclasses to ==0.6, which was released in 2018. This can cause version conflicts with other packages.

### Steps To Reproduce
Install dbt with any package that expects a more recent version of dataclasses.

### Expected behavior
No version conflict.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**Comment by jtcohen6** [comment]
Copying here from https://github.com/fishtown-analytics/dbt/issues/3150:

> If you wanted to bump the `dataclasses` dependency in dbt, you could:
> 1. Fork `hologram`, bump [its `dataclasses` dependency](https://github.com/fishtown-analytics/hologram/blob/2adee957e4cd2cddbb845492d40b78ebc5d9b29d/setup.py#L6), open a PR against it
> 2. Open a PR against fishtown-analytics/dbt that replaces [the versioned `hologram` dependency](https://github.com/fishtown-analytics/dbt/blob/b70fb543f5825744b7705009aef815b8071ab516/core/setup.py#L73) with a `git+` pointer to your fork branch
> 3. Assuming all CI checks pass in the dbt PR, we can merge the hologram PR, cut a new version, and update the dbt PR to point to that new version.
> 
> By the by, both of the `dataclasses` dependencies (in `hologram` and in `dbt-core`) are written as:
> ```python
> 'dataclasses==0.6;python_version<"3.7"'
> ```
> The dataclass functionality is native to python 3.7 and above; the `dataclasses` library is just a backport for python 3.6. So users should only be experiencing version conflict if they're using python 3.6. Also, [python 3.6 end of life](https://www.python.org/dev/peps/pep-0494/#lifespan) is December 2021 (9 months from now).
